{% set version = "0.15.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/myst-parser/myst-parser-{{ version }}.tar.gz
  sha256: f7f3b2d62db7655cde658eb5d62b2ec2a4631308137bd8d10f296a40d57bbbeb

build:
  number: 0
  entry_points:
    - myst-benchmark = myst_parser.cli.benchmark:main
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - docutils >=0.15,<0.18
    - markdown-it-py >=1.0,<2.0.0
    - mdit-py-plugins >=0.2.8,<0.3
    - jinja2
    - python >=3.6
    - pyyaml
    - sphinx >=3.1,<5

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - myst_parser
    - myst_parser.cli

about:
  home: https://github.com/ExecutableBookProject/MyST-Parser
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An extended commonmark compliant parser, with bridges to docutils & sphinx.
  doc_url: https://myst-parser.readthedocs.io

extra:
  recipe-maintainers:
    - chrisjsewell
    - choldgraf
    - conda-forge/jupyter-book
